name: CI

on:
  push:
    branches: [main, scaffold/**]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - name: Verify go.mod
        run: go mod tidy && git diff --exit-code

      - name: Build
        run: go build ./...

      - name: Vet
        run: go vet ./...
